name: Build
on:
  push:
    paths-ignore:
      - docs/**
      - .github/workflows/docs.yml
jobs:
  build:
    name: Build Traffic
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        build-type: [Debug, Release, RelWithDebInfo]
        version: [7, 9]
        sanitizer: [ASAN, UBSAN]
    env:
      CMAKE_GENERATOR: Ninja
      GITHUB_TOKEN: ${{github.token}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Package Index
        run: sudo apt-get update
      - name: Install CMake + Ninja
        run: sudo apt-get install --yes ninja-build cmake
      - name: libstdc++-10 workaround
        run: sudo apt-get remove g++-10
      - name: Install Toolchain
        run: >
          sudo apt-get install --yes
          clang-format-10
          clang-tools-10
          clang-tidy-10
          libc++-10-dev
          clang-10
          llvm-10
          lld-10
      - name: Select Download Build Type
        id: download
        run: echo "::set-output name=type::$(echo ${{matrix.build-type}} | tr '[:upper:]' '[:lower:]')"
      - name: Download Dependencies
        run: >
          gh release download
          --repo netlify/trafficserver
          --dir ${{github.workspace}}/packages
          --pattern *${{matrix.version}}*${{steps.download.outputs.type}}*.ddeb
          --pattern *${{matrix.version}}*${{steps.download.outputs.type}}*.deb
      - name: Install Dependencies
        run: sudo apt install --yes ${{github.workspace}}/packages/*.deb
      - name: Configure Project
        run: >
          cmake -B${{github.workspace}}/build -S${{github.workspace}}
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}}
          -DCMAKE_PREFIX_PATH=/opt/ts
          -DTRAFFIC_WITH_${{matrix.sanitizer}}=YES
      - name: Build Project
        run: cmake --build build
